name: 1 - ğŸ“œ test mock back

on:
    push:
        branches: ["1-mock-livres"]

defaults:
    run:
        working-directory: backend

jobs:
    test:
        name: ğŸ”§Test
        runs-on: ubuntu-latest

        steps:
            - name: ğŸ¤© Checkout repo
              uses: actions/checkout@v3
            
            - name: ğŸ™„ Installation des dÃ©pendances
              working-directory: backend
              run: npm install

            - name: ğŸ˜ Lancement des tests backend
              run: npm run test:ci